name: "Assert Actual Is Expected"
branding:
  icon: "target"
  color: "green"
description: "Write tests in GitHub Workflows for integration tests and build pipelines"
author: "Samuel Ryan <sam@samryan.co.uk>"
inputs:
  assertion:
    description: "Name of the assertion to run against value"
    required: true
  expected:
    description: "Value the assertion is looking for"
    required: false
  actual:
    description: "Dynamic value to test against"
    required: false
  type:
    description: "Javascript data type that actual and expected will be cast to"
    default: "string"
    required: true
  each:
    description: "Parse multi-line `actual` into many values and assert against each"
    default: "false"
    required: false
  local-path:
    description: "Path to assertions on the runner's filesystem"
    default: "${{ github.workspace }}"
    required: true
outputs:
  message:
    description: "Human readable result of the assertion"
  pass:
    description: "Boolean describing whether the assertion passed"
runs:
  using: "node12"
  main: "dist/index.js"
