name: "Test Action"

on:
  push:
    branches:
      - "**"

jobs:
  simple-is-equal-assertions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Developer is greeted
        uses: ./
        with:
          actual: "Hello, World!"
          expected: "Hello, World!"
          assertion: is-equal
      - name: Developer is dismissed
        uses: ./
        continue-on-error: true
        with:
          assertion: is-equal
          expected: "Goodbye, World!"
          actual: "Hello, World!"
