name: "Test Action"

on:
  push:
    branches:
      - "**"

env:
  greeting: "Hello, World!"
  dismissal: "Bye bye!"

jobs:
  simple-is-equal-assertions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test developer is greeted
        uses: ./
        with:
          assertion: workflows://is-equal
          actual: "${{ env.greeting }}"
          expected: "Hello, World!"
      - name: Test developer is dismissed
        uses: ./
        continue-on-error: true
        with:
          assertion: workflows://is-equal
          actual: "${{ env.dismissal }}"
          expected: "Goodbye, World!"
      - name: Test each line is the greeting
        uses: ./
        with:
          assertion: workflows://is-equal
          actual: |
            ${{ env.greeting }}
            ${{ env.greeting }}
            ${{ env.greeting }}
          expected: "${{ env.greeting }}"
          each: true
  workflows-file-assertions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test an even number is even
        uses: ./
        with:
          assertion: workflows://is-even
          actual: 2
          type: number
      - name: Test an odd number is not even
        continue-on-error: true
        uses: ./
        with:
          assertion: workflows://is-even
          actual: 3
          type: number
