name: "Tests (Integration)"

on:
  push:
    branches:
      - "**"

env:
  dist-path: "dist"

jobs:
  upload-dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Javascript dependencies with npm
        if: ${{ github.ref != 'refs/heads/release' }}
        run: npm install
      - name: Package action for integration tests
        if: ${{ github.ref != 'refs/heads/release' }}
        run: npm run package
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: ${{ env.dist-path }}
  test-local-assertion:
    runs-on: ubuntu-latest
    needs:
      - upload-dist
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: ${{ env.dist-path }}
      - name: Expect two equal values to pass an equality test
        uses: ./
        with:
          assertion: local://.github/workflows/assertions/is-equal
          actual: "Hello, World!"
          expected: "Hello, World!"
      - name: Expect two different values not to pass an equality test
        uses: ./
        continue-on-error: true
        with:
          assertion: local://.github/workflows/assertions/is-equal
          actual: "Bye bye!"
          expected: "Goodbye, World!"
      - name: Expect many values to each pass an equality test
        uses: ./
        with:
          assertion: local://.github/workflows/assertions/is-equal
          actual: |
            Hello, World!
            Hello, World!
            Hello, World!
          expected: "Hello, World!"
          each: true
  test-type-based-assertion:
    runs-on: ubuntu-latest
    needs:
      - upload-dist
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: ${{ env.dist-path }}
      - name: Expect value to be tested as type
        uses: ./
        with:
          assertion: local://.github/workflows/assertions/is-even
          actual: 2
          type: number
  test-npm-assertion:
    runs-on: ubuntu-latest
    needs:
      - upload-dist
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: ${{ env.dist-path }}
      - name: Expect two equal values to pass an equality test using an assertion from npm
        uses: ./
        with:
          assertion: npm://@assertions/is-equal
          actual: "Hello, World!"
          expected: "Hello, World!"
  test-readme-example:
    runs-on: ubuntu-latest
    needs:
      - upload-dist
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: ${{ env.dist-path }}
      - name: Generate SemVer aliases with prefix
        id: prefixed
        uses: pr-mpt/actions-semver-aliases@v1
        with:
          version: "3.14.1"
          prefix: "v"
          major: true
          minor: false
      - name: Assert alias is prefixed
        uses: ./
        with:
          assertion: npm://@assertions/starts-with
          each: true
          actual: "${{ steps.prefixed.outputs.list }}"
          expected: "v"
  test-outputs:
    runs-on: ubuntu-latest
    needs:
      - upload-dist
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: ${{ env.dist-path }}
      - id: equal-strings
        uses: ./
        with:
          assertion: local://.github/workflows/assertions/is-equal
          actual: "Hello, World!"
          expected: "Hello, World!"
      - name: Test `message` output is set from Result `message`
        uses: ./
        with:
          assertion: npm://@assertions/is-equal
          actual: "${{ steps.equal-strings.outputs.message }}"
          expected: "compared Hello, World! to Hello, World!"
      - name: Test `pass` output is set from Result `pass`
        uses: ./
        with:
          assertion: npm://@assertions/is-equal
          actual: "${{ steps.equal-strings.outputs.pass }}"
          expected: "true"
