name: "Test Action"

on:
  push:
    branches:
      - "**"

jobs:
  simple-is-equal-assertions:
    runs-on: ubuntu-latest
    env:
      greeting: "Hello, World!"
      dismissal: "Bye bye!"
    steps:
      - uses: actions/checkout@v2
      - name: Test developer is greeted
        uses: ./
        with:
          assertion: is-equal
          actual: "${{ env.greeting }}"
          expected: "Hello, World!"
      - name: Test developer is dismissed
        uses: ./
        continue-on-error: true
        with:
          assertion: is-equal
          actual: "${{ env.dismissal }}"
          expected: "Goodbye, World!"
      - name: Test each line is the greeting
        uses: ./
        with:
          assertion: is-equal
          actual: |
            ${{ env.greeting }}
            ${{ env.greeting }}
            ${{ env.greeting }}
          expected: "${{ env.greeting }}"
          each: true
