name: "Test Action"

on:
  push:
    branches:
      - "**"

jobs:
  test-action-runs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run all
      - uses: ./
        with:
          assertion: is-equal
          expected: "Hello, World!"
          actual: "Hello, World!"
